### PR TITLE
Rewrite docs examples with commented code to use diffs

### PR DESCRIPTION
**Pull request by adamchainz**
The diff format has been used for most new features and I find it much easier to read.

### CODE REVIEW

**Comment by asottile** [comment]
the commented approach is quite a bit more succinct when there's many examples or when they're multi-line examples

**Comment by adamchainz** [comment]
This is true but I think that doesn't balance out the lack of readability. GitHub renders the comments faded out and italic by default, which makes comparison harder.

A table format could work for brevity. I'm also happy to remove the blank lines I've added here.

**Comment by MarcoGorelli** [comment]
For what my opinion's worth, I think this is an improvement - the first time I stumbled upon this repo I couldn't tell what the comments were meant to be, it only made sense to me when I saw the diffs

**Comment by hugovk** [comment]
https://github.com/asottile/setup-cfg-fmt#what-does-it-do also uses `diff` which looks good.

**Comment by asottile** [comment]
yeah I guess removing the whitespace would be better?

**Comment by adamchainz** [comment]
I removed the newlines that I addeed.

**Review by asottile — APPROVED** [review]

**Comment by mxr** [comment]
@adamchainz any thoughts on this section that uses input/output instead of diffs?

https://github.com/asottile/pyupgrade/blob/ccf3a9192fca6d2883b1e67d785e0010243e30c3/README.md#python2-and-old-python3x-blocks

**Comment by adamchainz** [comment]
It could look better as a diff, idk, try it out?

**Pull request merged**
