### PR TITLE
Rewrite unittest deprecated aliases

### LINKED ISSUE #519: unittest deprecated aliases
`unittest` has a bunch of deprecated aliases: https://docs.python.org/3.9/library/unittest.html#deprecated-aliases

Any use triggers deprecation warnings in one's test suite:

```
/.../test_example.py:6: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(1, 1)
```

It would be nice to rewrite those.

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #519.

### CODE REVIEW

**Comment by adamchainz** [comment]
I was thinking of trying a little harder to detect whether we're inside a `unittest` TestCase, but it's hard since users often use subclasses of `TestCase` e.g. via Django, or project specific.

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Hey @adamchainz 

Quick comment before Anthony's review - I expect you'll be asked to provide `noop` test cases for when pyupgrade isn't expected to do a rewrite (see other test files for examples)

**Comment by adamchainz** [comment]
Very true. One of my tests was even a 'noop' test already, I just didn't write it as such.

**Review by asottile — APPROVED** [review]

**Pull request merged**
