### PR TITLE
Test against Python 3.7

### PR DESCRIPTION
**Pull request by sloria**
Also, improve formatting for better vertical alignment

### CODE REVIEW

**Comment by asottile** [comment]
- [we're already testing against py37 on windows](https://github.com/asottile/pyupgrade/blob/bf9aa8f3fdabcd34542ba1de829759b6addb4bef/appveyor.yml#L4)
- [`sudo: true` is no longer necessary for `dist: xenial`](https://github.com/deadsnakes/travis-ci-python3.7-example#update-2018-07-03)
- I'd rather keep the indentation that's already there, it's at least consistent with my other projects
- I plan to move all my projects to py27 + py37 once I don't have to jump through hoops for travis

so probably won't do this now? and then later I'll automate it with [all-repos](https://github.com/asottile/all-repos) -- so, thanks for the PR 🎉 but probably not today :(

**Comment by sloria** [comment]
Cool cool. TIL `sudo: true` is no longer necessary for `dist: xenial`. 👍

**Comment by asottile** [comment]
<3 thank you though the PR is still appreciated!

**Comment by hugovk** [comment]
`sudo:` is no longer needed, full stop.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Personally, I would add 3.7 to Travis: if a contributor is going to turn on a CI before submitting, it's more likely to be Travis than AppVeyor. Also, it's still inside the 5 job limit, and who knows when you might find a bug on 3.7 on Linux but not Windows?

**Comment by asottile** [comment]
didn't know they had progressed their migration so quickly

cleaned it from all my repos 🎉 https://github.com/asottile/all-repos-incantations#travis-remove-sudo

**Pull request closed without merging**
