### PR TITLE
Include license file in the generated wheel package

### PR DESCRIPTION
**Pull request by jdufresne**
The wheel package format supports including the license file. This is
done using the [metadata] section in the setup.cfg file. For additional
information on this feature, see:

https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file

Helps project comply with its own license:

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

### CODE REVIEW

**Comment by asottile** [comment]
as far as I can tell this is unnecessary:

```console
$ ~/opt/venv/bin/pip freeze --all | grep setuptools
setuptools==40.6.2
$ ~/opt/venv/bin/python setup.py bdist_wheel
...
$ cd dist && unzip *.whl
...
$ head -1 pyupgrade-1.11.0.dist-info/LICENSE 
Copyright (c) 2017 Anthony Sottile
```

the wheel on pypi also contains this already:

```
$ ~/opt/venv/bin/pip download pyupgrade --no-deps && unzip -l *.whl
Collecting pyupgrade
  Downloading https://files.pythonhosted.org/packages/a2/52/a8c01c4b0b986c14ad919ce17e2d43d0d3ab57d26bd88a8c24b0e3619d45/pyupgrade-1.11.0-py2.py3-none-any.whl
  Saved ./pyupgrade-1.11.0-py2.py3-none-any.whl
Successfully downloaded pyupgrade
Archive:  pyupgrade-1.11.0-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    43419  2018-11-25 00:05   pyupgrade.py
     1059  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/LICENSE
      697  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/METADATA
      110  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/WHEEL
       46  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/entry_points.txt
       10  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/top_level.txt
      569  2018-11-25 00:06   pyupgrade-1.11.0.dist-info/RECORD
---------                     -------
    45910                     7 files
```

**Comment by asottile** [comment]
yeah, the important part from the docs you linked:

> By default, `wheel` conveniently includes files matching the following glob patterns in the `.dist-info` directory:
> -    `AUTHORS*`
> -    `COPYING*`
> -    `LICEN[CS]E*`
> -    `NOTICE*`

**Comment by jdufresne** [comment]
Interesting. The automatic inclusion of LICENSE must be a new feature. It didn't do that in previous versions.

**Comment by jdufresne** [comment]
I have removed the changes to `setup.cfg`. Still adds `license=` to setuptools.

**Comment by asottile** [comment]
Thanks!

**Pull request merged**
