### PR TITLE
Add opt-out for conversion of str.encode('utf-8') to str.encode()

### PR DESCRIPTION
**Pull request by hexagonrecursion**
pip does not want this https://github.com/pypa/pip/pull/9766#discussion_r606243093

### CODE REVIEW

**Comment by asottile** [comment]
no thanks -- the existing options are for breakages only.  this is an opinionated tool without preferences

**Comment by hexagonrecursion** [comment]
But pip prefers `str.encode('utf-8')` over `str.encode()` on the basis that explicit is better then implicit. What should I do?

Would you be interested in a PR that makes upupgrade leave `str.encode('utf-8')` alone and convert  `str.encode()` to `str.encode('utf-8')` unconditionally?

**Comment by asottile** [comment]
> But pip prefers `str.encode('utf-8')` over `str.encode()` on the basis that explicit is better then implicit. What should I do?

the whole point of opinionated tools is to not have a discussion about things. if they don't like the opinions then don't use the tool.


> Would you be interested in a PR that makes upupgrade leave `str.encode('utf-8')` alone and convert `str.encode()` to `str.encode('utf-8')` unconditionally?

no, that's worse in every way

**Comment by hexagonrecursion** [comment]
understood

**Pull request closed without merging**
