### PR TITLE
Add --version/-V option

### PR DESCRIPTION
**Pull request by atugushev**

### CODE REVIEW

**Comment by asottile** [comment]
does this provide anything over `pip freeze | grep pyupgrade`?

**Comment by atugushev** [comment]
Nope, It's the same. I've run `pyupgrade --version` a few times and annoyed that there was no that option. OTOH, it might be too much to bring the new dep for this simple stuff :)

**Comment by asottile** [comment]
:man_shrugging: yeah I think using `pip` is probably sufficient

**Comment by asottile** [comment]
thanks for the PR nonetheless!

**Pull request closed without merging**
