### PR TITLE
Remove erroneous string in test cases

### PR DESCRIPTION
**Pull request by mxr**

### CODE REVIEW

**Comment by asottile** [comment]
this is intentional, a noop test case that the empty string is not changed

**Comment by mxr** [comment]
TIL

**Comment by mxr** [comment]
Why is it in that set of test cases?

**Comment by asottile** [comment]
the noop tests?

**Comment by mxr** [comment]
It's in the named tuple tests file, but `''` isn't specific to named tuples?

**Comment by asottile** [comment]
it broke while I was implementing the namedtuple check

**Comment by mxr** [comment]
🤯

**Pull request closed without merging**
