### PR TITLE
dont rewrite universal_newlines if text or **kwargs present 

### LINKED ISSUE #610: universal_newlines conversion can lead to doubled "text"
If for some reason `universal_newlines` and `text` are both passed to a `subprocess.run()`, replacing the first with the latter causes `text` to be doubled. I suggest to in such case remove `universal_newlines`, if `text` has priority anyway with Python 3.6 and later.

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #610

### CODE REVIEW

**Comment by asottile** [comment]
I think it should maybe just skip in this case (and with `**kwargs`) -- in OP's example it would have broken `their_subprocess_wrapper(universal_newlines=True)`

thoughts?

**Comment by MarcoGorelli** [comment]
Yes, agreed - that would be simpler, and also more consistent with what I understand pyupgrade's ethos to be (not changing code's behaviour but instead just burning bridges)

**Review by asottile — APPROVED** [review]

**Comment by MichaIng** [comment]
Many thanks for solving this. I wonder whether `universal_newlines` has any effect on modern Python versions if `text` is defined as well. It is indeed the most conservative approach to not touch it, but it could be helpful to simply remove it for developers to recognise that it is obsolete (if it really is).

**Comment by asottile** [comment]
pyupgrade aims to not break code, even if the rewrite is helpful we err on the side of "maybe the developer won't look at the changes or have tests covering the behaviours"

**Comment by MichaIng** [comment]
Okay, fair enough 🙂.

**Pull request merged**
